blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCommentView

app_name = 'blogs'

urlpatterns = [
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment'),
    path('<int:pk>/post/', BlogDetailView.as_view(), name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shops')),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('', include('pages.urls', namespace='pages')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'pages'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('', HomePageView.as_view(), name='home'),
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView

app_name = 'shops'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('<int:pk>/detail/', ProductDetailView.as_view(), name='product_detail')
]

templates/layouts/navbar.html
{% load static %}

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Free shipping, 30-day return or refund guarantee.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            <a href="#">Sign in</a>
                            <a href="#">FAQs</a>
                        </div>
                        <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>USD</li>
                                <li>EUR</li>
                                <li>USD</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li {% if request.path == '/' %}class="active"{% endif %}>
                            <a href="{% url 'pages:home' %}">Home</a>
                        </li>
                        <li {% if request.path == '/shop/' %}class="active"{% endif %}>
                            <a href="{% url 'shops:shop' %}">Shop</a>
                        </li>
                        <li {% if request.path == '/blog/' %}class="active"{% endif %}>
                            <a href="{% url 'blogs:blog_list' %}">Blog</a>
                        </li>
                        <li {% if request.path == '/about/' %}class="active"{% endif %}>
                            <a href="{% url 'pages:about' %}">About Us</a>
                        </li>
                        <li {% if request.path == '/contact/' %}class="active"{% endif %}>
                            <a href="{% url 'pages:contact' %}">Contacts</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                    <div class="price">$0.00</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/shop_sidebar.html
<div class="shop__sidebar__search">
    <form action="{% url 'shops:shop' %}">
        <input value="{{ request.GET.q }}" name="q" type="text" placeholder="Search...">
        <button type="submit"><span class="icon_search"></span></button>
    </form>
</div>
<div class="shop__sidebar__accordion">
    <div class="accordion" id="accordionExample">
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
            </div>
            <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__categories">
                        <ul class="nice-scroll">
                            {% for category in categories %}
                                <li><a {% if request.GET.cat == category.pk|stringformat:'i' %} class="text-dark" {% endif %} href="?cat={{ category.pk }}">{{ category }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
            </div>
            <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__brand">
                        <ul>
                            {% for b in brands %}
                                <li><a {% if request.GET.brand == b.pk|stringformat:'i' %} class="text-dark" {% endif %} href="?brand={{ b.pk }}">{{ b }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
            </div>
            <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__price">
                        <ul>
                            <li><a href="#">$0.00 - $50.00</a></li>
                            <li><a href="#">$50.00 - $100.00</a></li>
                            <li><a href="#">$100.00 - $150.00</a></li>
                            <li><a href="#">$150.00 - $200.00</a></li>
                            <li><a href="#">$200.00 - $250.00</a></li>
                            <li><a href="#">250.00+</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFour">Size</a>
            </div>
            <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__size">
                        <label for="xs">xs
                            <input type="radio" id="xs">
                        </label>
                        <label for="sm">s
                            <input type="radio" id="sm">
                        </label>
                        <label for="md">m
                            <input type="radio" id="md">
                        </label>
                        <label for="xl">xl
                            <input type="radio" id="xl">
                        </label>
                        <label for="2xl">2xl
                            <input type="radio" id="2xl">
                        </label>
                        <label for="xxl">xxl
                            <input type="radio" id="xxl">
                        </label>
                        <label for="3xl">3xl
                            <input type="radio" id="3xl">
                        </label>
                        <label for="4xl">4xl
                            <input type="radio" id="4xl">
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
            </div>
            <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__color">
                        <label class="c-1" for="sp-1">
                            <input type="radio" id="sp-1">
                        </label>
                        <label class="c-2" for="sp-2">
                            <input type="radio" id="sp-2">
                        </label>
                        <label class="c-3" for="sp-3">
                            <input type="radio" id="sp-3">
                        </label>
                        <label class="c-4" for="sp-4">
                            <input type="radio" id="sp-4">
                        </label>
                        <label class="c-5" for="sp-5">
                            <input type="radio" id="sp-5">
                        </label>
                        <label class="c-6" for="sp-6">
                            <input type="radio" id="sp-6">
                        </label>
                        <label class="c-7" for="sp-7">
                            <input type="radio" id="sp-7">
                        </label>
                        <label class="c-8" for="sp-8">
                            <input type="radio" id="sp-8">
                        </label>
                        <label class="c-9" for="sp-9">
                            <input type="radio" id="sp-9">
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
            </div>
            <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__tags">
                        {% for tag in tags %}
                            <a
                                    {% if request.GET.tag == tag.name %}style="background: #000; color: #fff;"
                                    {% endif %} href="?tag={{ tag }}">{{ tag }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>